version: 2.1
workflows:
    work:
        jobs:
            - build
            - lint: 
                requires: 
                - build
            - test:
                requires:
                    - build

jobs:
    build:
        docker:
            - image: cimg/node:12.18
        steps:
            - checkout
            - restore_cache:
                key: yarn-packages-v1{{ checksum "yarn.lock" }}
            - run: yarn global add node-gyp && yarn install
            - save_cache:
                key: yarn-packages-v2{{ checksum "yarn.lock" }}
                paths:
                    - ./node_modules
    lint:
        docker:
            - image: cimg/node:12.18
        steps:
            - checkout
            - restore_cache:
                key: yarn-packages-v2{{ checksum "yarn.lock" }}
            - run: yarn lint && yarn format:check

    test:
        docker:
            - image: cimg/node:12.18
        steps:
            - checkout
            - restore_cache:
                key: yarn-packages-v2{{ checksum "yarn.lock" }}
            - run: yarn test:ci
     