version: 2.1

jobs:
  build: 
    machine:
      image: windows-default # Windows machine image
    resource_class: windows.medium
    steps:
        - checkout
        - run: Write-Host 'Hello, Windows'