version: 2.1
workflows:
  build_and_test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - tests:
          requires:
            - build
      - db
      - e2e:
          requires:
            - db
jobs:
  build:
    docker:
      - image: cimg/node:14.10.1
    steps:
      - checkout
      - restore_cache:
          key: yarn-packages-v2{{ checksum "yarn.lock" }}
      - run: yarn global add node-gyp && yarn install
      - save_cache:
          key: yarn-packages-v2{{ checksum "yarn.lock" }}      
          paths:
            - ./node_modules
  tests:
    docker:
      - image: cimg/node:14.10.1
    steps: 
      - checkout
      - restore_cache:
          key: yarn-packages-v2{{ checksum "yarn.lock" }}
      - run: yarn test:ci
      - save_cache:
          key: yarn-packages-v2{{ checksum "yarn.lock" }}      
          paths:
            - ./node_modules
  lint:
    docker:
      - image: cimg/node:14.10.1
    steps:
      - checkout
      - restore_cache:
          key: yarn-packages-v2{{ checksum "yarn.lock" }}
      - run: yarn lint && yarn format:check
      - save_cache:
          key: yarn-packages-v2{{ checksum "yarn.lock" }}      
          paths:
            - ./node_modules
  db:
    docker:
      - image: circleci/postgres:alpine
        environment:
          PG_USER: circleci-demo-go
          PG_DB: circle_test
          PG_PWD: toto
    steps:
      - checkout
      - restore_cache:
          key: yarn-packages-v2{{ checksum "yarn.lock" }}
      
      - save_cache:
          key: yarn-packages-v2{{ checksum "yarn.lock" }}      
          paths:
            - ./node_modules
  e2e:
    docker:
      - image: cimg/node:14.10.1 
    steps:
      - checkout
      - restore_cache:
          key: yarn-packages-v2{{ checksum "yarn.lock" }}
      - run: 
          command: yarn test:e2e  
          environment:
            DATABASE_URL: postgres://${PG_USER}:${PG_PWD}@localhost:5432/${PG_DB}
            JWT_SECRET: yeet
            API_PORT: 3000
            API_HOST: localhost
            API_PROTOCOL: http
      - save_cache:
          key: yarn-packages-v2{{ checksum "yarn.lock" }}      
          paths:
            - ./node_modules